# SkanBlogBundle_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: SkanBlogBundle:Default:index }

SkanBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: SkanBlogBundle:Page:index }
    requirements:
        _method: GET
